<?php

/**
 * These are just the language codes, not regions. This means it only lists en, not en-US, en-CA etc.
 * @see http://www.iana.org/assignments/language-subtag-registry
 */
$global['langs_codes'] = array(
    array('value'=>'af_NA','label'=>'Afrikaans (Namibia)', 'flag'=>'na'),
    array('value'=>'af_ZA','label'=>'Afrikaans (South Africa)', 'flag'=>'za'),
    array('value'=>'af','label'=>'Afrikaans', 'flag'=>'af'),
    array('value'=>'ak_GH','label'=>'Akan (Ghana)', 'flag'=>'gh'),
    array('value'=>'ak','label'=>'Akan', 'flag'=>'ak'),
    array('value'=>'sq_AL','label'=>'Albanian (Albania)', 'flag'=>'al'),
    array('value'=>'sq','label'=>'Albanian', 'flag'=>'sq'),
    array('value'=>'am_ET','label'=>'Amharic (Ethiopia)', 'flag'=>'et'),
    array('value'=>'am','label'=>'Amharic', 'flag'=>'am'),
    array('value'=>'ar_DZ','label'=>'Arabic (Algeria)', 'flag'=>'dz'),
    array('value'=>'ar_BH','label'=>'Arabic (Bahrain)', 'flag'=>'bh'),
    array('value'=>'ar_EG','label'=>'Arabic (Egypt)', 'flag'=>'eg'),
    array('value'=>'ar_IQ','label'=>'Arabic (Iraq)', 'flag'=>'iq'),
    array('value'=>'ar_JO','label'=>'Arabic (Jordan)', 'flag'=>'jo'),
    array('value'=>'ar_KW','label'=>'Arabic (Kuwait)', 'flag'=>'kw'),
    array('value'=>'ar_LB','label'=>'Arabic (Lebanon)', 'flag'=>'lb'),
    array('value'=>'ar_LY','label'=>'Arabic (Libya)', 'flag'=>'ly'),
    array('value'=>'ar_MA','label'=>'Arabic (Morocco)', 'flag'=>'ma'),
    array('value'=>'ar_OM','label'=>'Arabic (Oman)', 'flag'=>'om'),
    array('value'=>'ar_QA','label'=>'Arabic (Qatar)', 'flag'=>'qa'),
    array('value'=>'ar_SA','label'=>'Arabic (Saudi Arabia)', 'flag'=>'sa'),
    array('value'=>'ar_SD','label'=>'Arabic (Sudan)', 'flag'=>'sd'),
    array('value'=>'ar_SY','label'=>'Arabic (Syria)', 'flag'=>'sy'),
    array('value'=>'ar_TN','label'=>'Arabic (Tunisia)', 'flag'=>'tn'),
    array('value'=>'ar_AE','label'=>'Arabic (United Arab Emirates)', 'flag'=>'ae'),
    array('value'=>'ar_YE','label'=>'Arabic (Yemen)', 'flag'=>'ye'),
    array('value'=>'ar','label'=>'Arabic', 'flag'=>'ar'),
    array('value'=>'hy_AM','label'=>'Armenian (Armenia)', 'flag'=>'am'),
    array('value'=>'hy','label'=>'Armenian', 'flag'=>'hy'),
    array('value'=>'as_IN','label'=>'Assamese (India)', 'flag'=>'in'),
    array('value'=>'as','label'=>'Assamese', 'flag'=>'as'),
    array('value'=>'asa_TZ','label'=>'Asu (Tanzania)', 'flag'=>'tz'),
    array('value'=>'asa','label'=>'Asu', 'flag'=>'asa'),
    array('value'=>'az_Cyrl','label'=>'Azerbaijani (Cyrillic)', 'flag'=>'cyrl'),
    array('value'=>'az_Cyrl_AZ','label'=>'Azerbaijani (Cyrillic, Azerbaijan)', 'flag'=>'az'),
    array('value'=>'az_Latn','label'=>'Azerbaijani (Latin)', 'flag'=>'latn'),
    array('value'=>'az_Latn_AZ','label'=>'Azerbaijani (Latin, Azerbaijan)', 'flag'=>'az'),
    array('value'=>'az','label'=>'Azerbaijani', 'flag'=>'az'),
    array('value'=>'bm_ML','label'=>'Bambara (Mali)', 'flag'=>'ml'),
    array('value'=>'bm','label'=>'Bambara', 'flag'=>'bm'),
    array('value'=>'eu_ES','label'=>'Basque (Spain)', 'flag'=>'es'),
    array('value'=>'eu','label'=>'Basque', 'flag'=>'eu'),
    array('value'=>'be_BY','label'=>'Belarusian (Belarus)', 'flag'=>'by'),
    array('value'=>'be','label'=>'Belarusian', 'flag'=>'be'),
    array('value'=>'bem_ZM','label'=>'Bemba (Zambia)', 'flag'=>'zm'),
    array('value'=>'bem','label'=>'Bemba', 'flag'=>'bem'),
    array('value'=>'bez_TZ','label'=>'Bena (Tanzania)', 'flag'=>'tz'),
    array('value'=>'bez','label'=>'Bena', 'flag'=>'bez'),
    array('value'=>'bn_BD','label'=>'Bengali (Bangladesh)', 'flag'=>'bd'),
    array('value'=>'bn_IN','label'=>'Bengali (India)', 'flag'=>'in'),
    array('value'=>'bn','label'=>'Bengali', 'flag'=>'bn'),
    array('value'=>'bs_BA','label'=>'Bosnian (Bosnia and Herzegovina)', 'flag'=>'ba'),
    array('value'=>'bs','label'=>'Bosnian', 'flag'=>'bs'),
    array('value'=>'bg_BG','label'=>'Bulgarian (Bulgaria)', 'flag'=>'bg'),
    array('value'=>'bg','label'=>'Bulgarian', 'flag'=>'bg'),
    array('value'=>'my_MM','label'=>'Burmese (Myanmar [Burma])', 'flag'=>'mm'),
    array('value'=>'my','label'=>'Burmese', 'flag'=>'my'),
    array('value'=>'yue_Hant_HK','label'=>'Cantonese (Traditional, Hong Kong SAR China)', 'flag'=>'hk'),
    array('value'=>'ca_ES','label'=>'Catalan (Spain)', 'flag'=>'es'),
    array('value'=>'ca','label'=>'Catalan', 'flag'=>'ca'),
    array('value'=>'tzm_Latn','label'=>'Central Morocco Tamazight (Latin)', 'flag'=>'latn'),
    array('value'=>'tzm_Latn_MA','label'=>'Central Morocco Tamazight (Latin, Morocco)', 'flag'=>'ma'),
    array('value'=>'tzm','label'=>'Central Morocco Tamazight', 'flag'=>'tzm'),
    array('value'=>'chr_US','label'=>'Cherokee (United States)', 'flag'=>'us'),
    array('value'=>'chr','label'=>'Cherokee', 'flag'=>'chr'),
    array('value'=>'cgg_UG','label'=>'Chiga (Uganda)', 'flag'=>'ug'),
    array('value'=>'cgg','label'=>'Chiga', 'flag'=>'cgg'),
    array('value'=>'zh_Hans','label'=>'Chinese (Simplified Han)', 'flag'=>'hans'),
    array('value'=>'zh_Hans_CN','label'=>'Chinese (Simplified Han, China)', 'flag'=>'cn'),
    array('value'=>'zh_Hans_HK','label'=>'Chinese (Simplified Han, Hong Kong SAR China)', 'flag'=>'hk'),
    array('value'=>'zh_Hans_MO','label'=>'Chinese (Simplified Han, Macau SAR China)', 'flag'=>'mo'),
    array('value'=>'zh_Hans_SG','label'=>'Chinese (Simplified Han, Singapore)', 'flag'=>'sg'),
    array('value'=>'zh_Hant','label'=>'Chinese (Traditional Han)', 'flag'=>'hant'),
    array('value'=>'zh_Hant_HK','label'=>'Chinese (Traditional Han, Hong Kong SAR China)', 'flag'=>'hk'),
    array('value'=>'zh_Hant_MO','label'=>'Chinese (Traditional Han, Macau SAR China)', 'flag'=>'mo'),
    array('value'=>'zh_Hant_TW','label'=>'Chinese (Traditional Han, Taiwan)', 'flag'=>'tw'),
    array('value'=>'zh','label'=>'Chinese', 'flag'=>'cn'),
    array('value'=>'kw_GB','label'=>'Cornish (United Kingdom)', 'flag'=>'gb'),
    array('value'=>'kw','label'=>'Cornish', 'flag'=>'kw'),
    array('value'=>'hr_HR','label'=>'Croatian (Croatia)', 'flag'=>'hr'),
    array('value'=>'hr','label'=>'Croatian', 'flag'=>'hr'),
    array('value'=>'cs_CZ','label'=>'Czech (Czech Republic)', 'flag'=>'cz'),
    array('value'=>'cs','label'=>'Czech', 'flag'=>'cz'),
    array('value'=>'da_DK','label'=>'Danish (Denmark)', 'flag'=>'dk'),
    array('value'=>'da','label'=>'Danish', 'flag'=>'da'),
    array('value'=>'nl_BE','label'=>'Dutch (Belgium)', 'flag'=>'be'),
    array('value'=>'nl_NL','label'=>'Dutch (Netherlands)', 'flag'=>'nl'),
    array('value'=>'nl','label'=>'Dutch', 'flag'=>'nl'),
    array('value'=>'ebu_KE','label'=>'Embu (Kenya)', 'flag'=>'ke'),
    array('value'=>'ebu','label'=>'Embu', 'flag'=>'ebu'),
    array('value'=>'en_AS','label'=>'English (American Samoa)', 'flag'=>'as'),
    array('value'=>'en_AU','label'=>'English (Australia)', 'flag'=>'au'),
    array('value'=>'en_BE','label'=>'English (Belgium)', 'flag'=>'be'),
    array('value'=>'en_BZ','label'=>'English (Belize)', 'flag'=>'bz'),
    array('value'=>'en_BW','label'=>'English (Botswana)', 'flag'=>'bw'),
    array('value'=>'en_CA','label'=>'English (Canada)', 'flag'=>'ca'),
    array('value'=>'en_GU','label'=>'English (Guam)', 'flag'=>'gu'),
    array('value'=>'en_HK','label'=>'English (Hong Kong SAR China)', 'flag'=>'hk'),
    array('value'=>'en_IN','label'=>'English (India)', 'flag'=>'in'),
    array('value'=>'en_IE','label'=>'English (Ireland)', 'flag'=>'ie'),
    array('value'=>'en_IL','label'=>'English (Israel)', 'flag'=>'il'),
    array('value'=>'en_JM','label'=>'English (Jamaica)', 'flag'=>'jm'),
    array('value'=>'en_MT','label'=>'English (Malta)', 'flag'=>'mt'),
    array('value'=>'en_MH','label'=>'English (Marshall Islands)', 'flag'=>'mh'),
    array('value'=>'en_MU','label'=>'English (Mauritius)', 'flag'=>'mu'),
    array('value'=>'en_NA','label'=>'English (Namibia)', 'flag'=>'na'),
    array('value'=>'en_NZ','label'=>'English (New Zealand)', 'flag'=>'nz'),
    array('value'=>'en_MP','label'=>'English (Northern Mariana Islands)', 'flag'=>'mp'),
    array('value'=>'en_PK','label'=>'English (Pakistan)', 'flag'=>'pk'),
    array('value'=>'en_PH','label'=>'English (Philippines)', 'flag'=>'ph'),
    array('value'=>'en_SG','label'=>'English (Singapore)', 'flag'=>'sg'),
    array('value'=>'en_ZA','label'=>'English (South Africa)', 'flag'=>'za'),
    array('value'=>'en_TT','label'=>'English (Trinidad and Tobago)', 'flag'=>'tt'),
    array('value'=>'en_UM','label'=>'English (U.S. Minor Outlying Islands)', 'flag'=>'um'),
    array('value'=>'en_VI','label'=>'English (U.S. Virgin Islands)', 'flag'=>'vi'),
    array('value'=>'en_GB','label'=>'English (United Kingdom)', 'flag'=>'gb'),
    array('value'=>'en_US','label'=>'English (United States)', 'flag'=>'us'),
    array('value'=>'en_ZW','label'=>'English (Zimbabwe)', 'flag'=>'zw'),
    array('value'=>'en','label'=>'English', 'flag'=>'us'),
    array('value'=>'eo','label'=>'Esperanto', 'flag'=>'eo'),
    array('value'=>'et_EE','label'=>'Estonian (Estonia)', 'flag'=>'ee'),
    array('value'=>'et','label'=>'Estonian', 'flag'=>'et'),
    array('value'=>'ee_GH','label'=>'Ewe (Ghana)', 'flag'=>'gh'),
    array('value'=>'ee_TG','label'=>'Ewe (Togo)', 'flag'=>'tg'),
    array('value'=>'ee','label'=>'Ewe', 'flag'=>'ee'),
    array('value'=>'fo_FO','label'=>'Faroese (Faroe Islands)', 'flag'=>'fo'),
    array('value'=>'fo','label'=>'Faroese', 'flag'=>'fo'),
    array('value'=>'fil_PH','label'=>'Filipino (Philippines)', 'flag'=>'ph'),
    array('value'=>'fil','label'=>'Filipino', 'flag'=>'fil'),
    array('value'=>'fi_FI','label'=>'Finnish (Finland)', 'flag'=>'fi'),
    array('value'=>'fi','label'=>'Finnish', 'flag'=>'fi'),
    array('value'=>'fr_BE','label'=>'French (Belgium)', 'flag'=>'be'),
    array('value'=>'fr_BJ','label'=>'French (Benin)', 'flag'=>'bj'),
    array('value'=>'fr_BF','label'=>'French (Burkina Faso)', 'flag'=>'bf'),
    array('value'=>'fr_BI','label'=>'French (Burundi)', 'flag'=>'bi'),
    array('value'=>'fr_CM','label'=>'French (Cameroon)', 'flag'=>'cm'),
    array('value'=>'fr_CA','label'=>'French (Canada)', 'flag'=>'ca'),
    array('value'=>'fr_CF','label'=>'French (Central African Republic)', 'flag'=>'cf'),
    array('value'=>'fr_TD','label'=>'French (Chad)', 'flag'=>'td'),
    array('value'=>'fr_KM','label'=>'French (Comoros)', 'flag'=>'km'),
    array('value'=>'fr_CG','label'=>'French (Congo - Brazzaville)', 'flag'=>'cg'),
    array('value'=>'fr_CD','label'=>'French (Congo - Kinshasa)', 'flag'=>'cd'),
    array('value'=>'fr_CI','label'=>'French (Côte d’Ivoire)', 'flag'=>'ci'),
    array('value'=>'fr_DJ','label'=>'French (Djibouti)', 'flag'=>'dj'),
    array('value'=>'fr_GQ','label'=>'French (Equatorial Guinea)', 'flag'=>'gq'),
    array('value'=>'fr_FR','label'=>'French (France)', 'flag'=>'fr'),
    array('value'=>'fr_GA','label'=>'French (Gabon)', 'flag'=>'ga'),
    array('value'=>'fr_GP','label'=>'French (Guadeloupe)', 'flag'=>'gp'),
    array('value'=>'fr_GN','label'=>'French (Guinea)', 'flag'=>'gn'),
    array('value'=>'fr_LU','label'=>'French (Luxembourg)', 'flag'=>'lu'),
    array('value'=>'fr_MG','label'=>'French (Madagascar)', 'flag'=>'mg'),
    array('value'=>'fr_ML','label'=>'French (Mali)', 'flag'=>'ml'),
    array('value'=>'fr_MQ','label'=>'French (Martinique)', 'flag'=>'mq'),
    array('value'=>'fr_MC','label'=>'French (Monaco)', 'flag'=>'mc'),
    array('value'=>'fr_NE','label'=>'French (Niger)', 'flag'=>'ne'),
    array('value'=>'fr_RW','label'=>'French (Rwanda)', 'flag'=>'rw'),
    array('value'=>'fr_RE','label'=>'French (Réunion)', 'flag'=>'re'),
    array('value'=>'fr_BL','label'=>'French (Saint Barthélemy)', 'flag'=>'bl'),
    array('value'=>'fr_MF','label'=>'French (Saint Martin)', 'flag'=>'mf'),
    array('value'=>'fr_SN','label'=>'French (Senegal)', 'flag'=>'sn'),
    array('value'=>'fr_CH','label'=>'French (Switzerland)', 'flag'=>'ch'),
    array('value'=>'fr_TG','label'=>'French (Togo)', 'flag'=>'tg'),
    array('value'=>'fr','label'=>'French', 'flag'=>'fr'),
    array('value'=>'ff_SN','label'=>'Fulah (Senegal)', 'flag'=>'sn'),
    array('value'=>'ff','label'=>'Fulah', 'flag'=>'ff'),
    array('value'=>'gl_ES','label'=>'Galician (Spain)', 'flag'=>'es'),
    array('value'=>'gl','label'=>'Galician', 'flag'=>'gl'),
    array('value'=>'lg_UG','label'=>'Ganda (Uganda)', 'flag'=>'ug'),
    array('value'=>'lg','label'=>'Ganda', 'flag'=>'lg'),
    array('value'=>'ka_GE','label'=>'Georgian (Georgia)', 'flag'=>'ge'),
    array('value'=>'ka','label'=>'Georgian', 'flag'=>'ka'),
    array('value'=>'de_AT','label'=>'German (Austria)', 'flag'=>'at'),
    array('value'=>'de_BE','label'=>'German (Belgium)', 'flag'=>'be'),
    array('value'=>'de_DE','label'=>'German (Germany)', 'flag'=>'de'),
    array('value'=>'de_LI','label'=>'German (Liechtenstein)', 'flag'=>'li'),
    array('value'=>'de_LU','label'=>'German (Luxembourg)', 'flag'=>'lu'),
    array('value'=>'de_CH','label'=>'German (Switzerland)', 'flag'=>'ch'),
    array('value'=>'de','label'=>'German', 'flag'=>'de'),
    array('value'=>'el_CY','label'=>'Greek (Cyprus)', 'flag'=>'cy'),
    array('value'=>'el_GR','label'=>'Greek (Greece)', 'flag'=>'gr'),
    array('value'=>'el','label'=>'Greek', 'flag'=>'gr'),
    array('value'=>'gu_IN','label'=>'Gujarati (India)', 'flag'=>'in'),
    array('value'=>'gu','label'=>'Gujarati', 'flag'=>'gu'),
    array('value'=>'guz_KE','label'=>'Gusii (Kenya)', 'flag'=>'ke'),
    array('value'=>'guz','label'=>'Gusii', 'flag'=>'guz'),
    array('value'=>'ha_Latn','label'=>'Hausa (Latin)', 'flag'=>'latn'),
    array('value'=>'ha_Latn_GH','label'=>'Hausa (Latin, Ghana)', 'flag'=>'gh'),
    array('value'=>'ha_Latn_NE','label'=>'Hausa (Latin, Niger)', 'flag'=>'ne'),
    array('value'=>'ha_Latn_NG','label'=>'Hausa (Latin, Nigeria)', 'flag'=>'ng'),
    array('value'=>'ha','label'=>'Hausa', 'flag'=>'ha'),
    array('value'=>'haw_US','label'=>'Hawaiian (United States)', 'flag'=>'us'),
    array('value'=>'haw','label'=>'Hawaiian', 'flag'=>'haw'),
    array('value'=>'he_IL','label'=>'Hebrew (Israel)', 'flag'=>'il'),
    array('value'=>'he','label'=>'Hebrew', 'flag'=>'il'),
    array('value'=>'hi_IN','label'=>'Hindi (India)', 'flag'=>'in'),
    array('value'=>'hi','label'=>'Hindi', 'flag'=>'hi'),
    array('value'=>'hu_HU','label'=>'Hungarian (Hungary)', 'flag'=>'hu'),
    array('value'=>'hu','label'=>'Hungarian', 'flag'=>'hu'),
    array('value'=>'is_IS','label'=>'Icelandic (Iceland)', 'flag'=>'is'),
    array('value'=>'is','label'=>'Icelandic', 'flag'=>'is'),
    array('value'=>'ig_NG','label'=>'Igbo (Nigeria)', 'flag'=>'ng'),
    array('value'=>'ig','label'=>'Igbo', 'flag'=>'ig'),
    array('value'=>'id_ID','label'=>'Indonesian (Indonesia)', 'flag'=>'id'),
    array('value'=>'id','label'=>'Indonesian', 'flag'=>'id'),
    array('value'=>'ga_IE','label'=>'Irish (Ireland)', 'flag'=>'ie'),
    array('value'=>'ga','label'=>'Irish', 'flag'=>'ga'),
    array('value'=>'it_IT','label'=>'Italian (Italy)', 'flag'=>'it'),
    array('value'=>'it_CH','label'=>'Italian (Switzerland)', 'flag'=>'ch'),
    array('value'=>'it','label'=>'Italian', 'flag'=>'it'),
    array('value'=>'ja_JP','label'=>'Japanese (Japan)', 'flag'=>'jp'),
    array('value'=>'ja','label'=>'Japanese', 'flag'=>'ja'),
    array('value'=>'kea_CV','label'=>'Kabuverdianu (Cape Verde)', 'flag'=>'cv'),
    array('value'=>'kea','label'=>'Kabuverdianu', 'flag'=>'kea'),
    array('value'=>'kab_DZ','label'=>'Kabyle (Algeria)', 'flag'=>'dz'),
    array('value'=>'kab','label'=>'Kabyle', 'flag'=>'kab'),
    array('value'=>'kl_GL','label'=>'Kalaallisut (Greenland)', 'flag'=>'gl'),
    array('value'=>'kl','label'=>'Kalaallisut', 'flag'=>'kl'),
    array('value'=>'kln_KE','label'=>'Kalenjin (Kenya)', 'flag'=>'ke'),
    array('value'=>'kln','label'=>'Kalenjin', 'flag'=>'kln'),
    array('value'=>'kam_KE','label'=>'Kamba (Kenya)', 'flag'=>'ke'),
    array('value'=>'kam','label'=>'Kamba', 'flag'=>'kam'),
    array('value'=>'kn_IN','label'=>'Kannada (India)', 'flag'=>'in'),
    array('value'=>'kn','label'=>'Kannada', 'flag'=>'kn'),
    array('value'=>'kk_Cyrl','label'=>'Kazakh (Cyrillic)', 'flag'=>'cyrl'),
    array('value'=>'kk_Cyrl_KZ','label'=>'Kazakh (Cyrillic, Kazakhstan)', 'flag'=>'kz'),
    array('value'=>'kk','label'=>'Kazakh', 'flag'=>'kk'),
    array('value'=>'km_KH','label'=>'Khmer (Cambodia)', 'flag'=>'kh'),
    array('value'=>'km','label'=>'Khmer', 'flag'=>'km'),
    array('value'=>'ki_KE','label'=>'Kikuyu (Kenya)', 'flag'=>'ke'),
    array('value'=>'ki','label'=>'Kikuyu', 'flag'=>'ki'),
    array('value'=>'rw_RW','label'=>'Kinyarwanda (Rwanda)', 'flag'=>'rw'),
    array('value'=>'rw','label'=>'Kinyarwanda', 'flag'=>'rw'),
    array('value'=>'kok_IN','label'=>'Konkani (India)', 'flag'=>'in'),
    array('value'=>'kok','label'=>'Konkani', 'flag'=>'kok'),
    array('value'=>'ko_KR','label'=>'Korean (South Korea)', 'flag'=>'kr'),
    array('value'=>'ko','label'=>'Korean', 'flag'=>'ko'),
    array('value'=>'khq_ML','label'=>'Koyra Chiini (Mali)', 'flag'=>'ml'),
    array('value'=>'khq','label'=>'Koyra Chiini', 'flag'=>'khq'),
    array('value'=>'ses_ML','label'=>'Koyraboro Senni (Mali)', 'flag'=>'ml'),
    array('value'=>'ses','label'=>'Koyraboro Senni', 'flag'=>'ses'),
    array('value'=>'lag_TZ','label'=>'Langi (Tanzania)', 'flag'=>'tz'),
    array('value'=>'lag','label'=>'Langi', 'flag'=>'lag'),
    array('value'=>'lv_LV','label'=>'Latvian (Latvia)', 'flag'=>'lv'),
    array('value'=>'lv','label'=>'Latvian', 'flag'=>'lv'),
    array('value'=>'lt_LT','label'=>'Lithuanian (Lithuania)', 'flag'=>'lt'),
    array('value'=>'lt','label'=>'Lithuanian', 'flag'=>'lt'),
    array('value'=>'luo_KE','label'=>'Luo (Kenya)', 'flag'=>'ke'),
    array('value'=>'luo','label'=>'Luo', 'flag'=>'luo'),
    array('value'=>'luy_KE','label'=>'Luyia (Kenya)', 'flag'=>'ke'),
    array('value'=>'luy','label'=>'Luyia', 'flag'=>'luy'),
    array('value'=>'mk_MK','label'=>'Macedonian (Macedonia)', 'flag'=>'mk'),
    array('value'=>'mk','label'=>'Macedonian', 'flag'=>'mk'),
    array('value'=>'jmc_TZ','label'=>'Machame (Tanzania)', 'flag'=>'tz'),
    array('value'=>'jmc','label'=>'Machame', 'flag'=>'jmc'),
    array('value'=>'kde_TZ','label'=>'Makonde (Tanzania)', 'flag'=>'tz'),
    array('value'=>'kde','label'=>'Makonde', 'flag'=>'kde'),
    array('value'=>'mg_MG','label'=>'Malagasy (Madagascar)', 'flag'=>'mg'),
    array('value'=>'mg','label'=>'Malagasy', 'flag'=>'mg'),
    array('value'=>'ms_BN','label'=>'Malay (Brunei)', 'flag'=>'bn'),
    array('value'=>'ms_MY','label'=>'Malay (Malaysia)', 'flag'=>'my'),
    array('value'=>'ms','label'=>'Malay', 'flag'=>'ms'),
    array('value'=>'ml_IN','label'=>'Malayalam (India)', 'flag'=>'in'),
    array('value'=>'ml','label'=>'Malayalam', 'flag'=>'ml'),
    array('value'=>'mt_MT','label'=>'Maltese (Malta)', 'flag'=>'mt'),
    array('value'=>'mt','label'=>'Maltese', 'flag'=>'mt'),
    array('value'=>'gv_GB','label'=>'Manx (United Kingdom)', 'flag'=>'gb'),
    array('value'=>'gv','label'=>'Manx', 'flag'=>'gv'),
    array('value'=>'mr_IN','label'=>'Marathi (India)', 'flag'=>'in'),
    array('value'=>'mr','label'=>'Marathi', 'flag'=>'mr'),
    array('value'=>'mas_KE','label'=>'Masai (Kenya)', 'flag'=>'ke'),
    array('value'=>'mas_TZ','label'=>'Masai (Tanzania)', 'flag'=>'tz'),
    array('value'=>'mas','label'=>'Masai', 'flag'=>'mas'),
    array('value'=>'mer_KE','label'=>'Meru (Kenya)', 'flag'=>'ke'),
    array('value'=>'mer','label'=>'Meru', 'flag'=>'mer'),
    array('value'=>'mfe_MU','label'=>'Morisyen (Mauritius)', 'flag'=>'mu'),
    array('value'=>'mfe','label'=>'Morisyen', 'flag'=>'mfe'),
    array('value'=>'naq_NA','label'=>'Nama (Namibia)', 'flag'=>'na'),
    array('value'=>'naq','label'=>'Nama', 'flag'=>'naq'),
    array('value'=>'ne_IN','label'=>'Nepali (India)', 'flag'=>'in'),
    array('value'=>'ne_NP','label'=>'Nepali (Nepal)', 'flag'=>'np'),
    array('value'=>'ne','label'=>'Nepali', 'flag'=>'ne'),
    array('value'=>'nd_ZW','label'=>'North Ndebele (Zimbabwe)', 'flag'=>'zw'),
    array('value'=>'nd','label'=>'North Ndebele', 'flag'=>'nd'),
    array('value'=>'nb_NO','label'=>'Norwegian Bokmål (Norway)', 'flag'=>'no'),
    array('value'=>'nb','label'=>'Norwegian Bokmål', 'flag'=>'nb'),
    array('value'=>'nn_NO','label'=>'Norwegian Nynorsk (Norway)', 'flag'=>'no'),
    array('value'=>'nn','label'=>'Norwegian Nynorsk', 'flag'=>'nn'),
    array('value'=>'nyn_UG','label'=>'Nyankole (Uganda)', 'flag'=>'ug'),
    array('value'=>'nyn','label'=>'Nyankole', 'flag'=>'nyn'),
    array('value'=>'or_IN','label'=>'Oriya (India)', 'flag'=>'in'),
    array('value'=>'or','label'=>'Oriya', 'flag'=>'or'),
    array('value'=>'om_ET','label'=>'Oromo (Ethiopia)', 'flag'=>'et'),
    array('value'=>'om_KE','label'=>'Oromo (Kenya)', 'flag'=>'ke'),
    array('value'=>'om','label'=>'Oromo', 'flag'=>'om'),
    array('value'=>'ps_AF','label'=>'Pashto (Afghanistan)', 'flag'=>'af'),
    array('value'=>'ps','label'=>'Pashto', 'flag'=>'ps'),
    array('value'=>'fa_AF','label'=>'Persian (Afghanistan)', 'flag'=>'af'),
    array('value'=>'fa_IR','label'=>'Persian (Iran)', 'flag'=>'ir'),
    array('value'=>'fa','label'=>'Persian', 'flag'=>'fa'),
    array('value'=>'pl_PL','label'=>'Polish (Poland)', 'flag'=>'pl'),
    array('value'=>'pl','label'=>'Polish', 'flag'=>'pl'),
    array('value'=>'pt_BR','label'=>'Portuguese (Brazil)', 'flag'=>'br'),
    array('value'=>'pt_GW','label'=>'Portuguese (Guinea-Bissau)', 'flag'=>'gw'),
    array('value'=>'pt_MZ','label'=>'Portuguese (Mozambique)', 'flag'=>'mz'),
    array('value'=>'pt_PT','label'=>'Portuguese (Portugal)', 'flag'=>'pt'),
    array('value'=>'pt','label'=>'Portuguese', 'flag'=>'pt'),
    array('value'=>'pa_Arab','label'=>'Punjabi (Arabic)', 'flag'=>'arab'),
    array('value'=>'pa_Arab_PK','label'=>'Punjabi (Arabic, Pakistan)', 'flag'=>'pk'),
    array('value'=>'pa_Guru','label'=>'Punjabi (Gurmukhi)', 'flag'=>'guru'),
    array('value'=>'pa_Guru_IN','label'=>'Punjabi (Gurmukhi, India)', 'flag'=>'in'),
    array('value'=>'pa','label'=>'Punjabi', 'flag'=>'pa'),
    array('value'=>'ro_MD','label'=>'Romanian (Moldova)', 'flag'=>'md'),
    array('value'=>'ro_RO','label'=>'Romanian (Romania)', 'flag'=>'ro'),
    array('value'=>'ro','label'=>'Romanian', 'flag'=>'ro'),
    array('value'=>'rm_CH','label'=>'Romansh (Switzerland)', 'flag'=>'ch'),
    array('value'=>'rm','label'=>'Romansh', 'flag'=>'rm'),
    array('value'=>'rof_TZ','label'=>'Rombo (Tanzania)', 'flag'=>'tz'),
    array('value'=>'rof','label'=>'Rombo', 'flag'=>'rof'),
    array('value'=>'ru_MD','label'=>'Russian (Moldova)', 'flag'=>'md'),
    array('value'=>'ru_RU','label'=>'Russian (Russia)', 'flag'=>'ru'),
    array('value'=>'ru_UA','label'=>'Russian (Ukraine)', 'flag'=>'ua'),
    array('value'=>'ru','label'=>'Russian', 'flag'=>'ru'),
    array('value'=>'rwk_TZ','label'=>'Rwa (Tanzania)', 'flag'=>'tz'),
    array('value'=>'rwk','label'=>'Rwa', 'flag'=>'rwk'),
    array('value'=>'saq_KE','label'=>'Samburu (Kenya)', 'flag'=>'ke'),
    array('value'=>'saq','label'=>'Samburu', 'flag'=>'saq'),
    array('value'=>'sg_CF','label'=>'Sango (Central African Republic)', 'flag'=>'cf'),
    array('value'=>'sg','label'=>'Sango', 'flag'=>'sg'),
    array('value'=>'seh_MZ','label'=>'Sena (Mozambique)', 'flag'=>'mz'),
    array('value'=>'seh','label'=>'Sena', 'flag'=>'seh'),
    array('value'=>'sr_Cyrl','label'=>'Serbian (Cyrillic)', 'flag'=>'cyrl'),
    array('value'=>'sr_Cyrl_BA','label'=>'Serbian (Cyrillic, Bosnia and Herzegovina)', 'flag'=>'ba'),
    array('value'=>'sr_Cyrl_ME','label'=>'Serbian (Cyrillic, Montenegro)', 'flag'=>'me'),
    array('value'=>'sr_Cyrl_RS','label'=>'Serbian (Cyrillic, Serbia)', 'flag'=>'rs'),
    array('value'=>'sr_Latn','label'=>'Serbian (Latin)', 'flag'=>'latn'),
    array('value'=>'sr_Latn_BA','label'=>'Serbian (Latin, Bosnia and Herzegovina)', 'flag'=>'ba'),
    array('value'=>'sr_Latn_ME','label'=>'Serbian (Latin, Montenegro)', 'flag'=>'me'),
    array('value'=>'sr_Latn_RS','label'=>'Serbian (Latin, Serbia)', 'flag'=>'rs'),
    array('value'=>'sr','label'=>'Serbian', 'flag'=>'sr'),
    array('value'=>'sn_ZW','label'=>'Shona (Zimbabwe)', 'flag'=>'zw'),
    array('value'=>'sn','label'=>'Shona', 'flag'=>'sn'),
    array('value'=>'ii_CN','label'=>'Sichuan Yi (China)', 'flag'=>'cn'),
    array('value'=>'ii','label'=>'Sichuan Yi', 'flag'=>'ii'),
    array('value'=>'si_LK','label'=>'Sinhala (Sri Lanka)', 'flag'=>'lk'),
    array('value'=>'si','label'=>'Sinhala', 'flag'=>'si'),
    array('value'=>'sk_SK','label'=>'Slovak (Slovakia)', 'flag'=>'sk'),
    array('value'=>'sk','label'=>'Slovak', 'flag'=>'sk'),
    array('value'=>'sl_SI','label'=>'Slovenian (Slovenia)', 'flag'=>'si'),
    array('value'=>'sl','label'=>'Slovenian', 'flag'=>'sl'),
    array('value'=>'xog_UG','label'=>'Soga (Uganda)', 'flag'=>'ug'),
    array('value'=>'xog','label'=>'Soga', 'flag'=>'xog'),
    array('value'=>'so_DJ','label'=>'Somali (Djibouti)', 'flag'=>'dj'),
    array('value'=>'so_ET','label'=>'Somali (Ethiopia)', 'flag'=>'et'),
    array('value'=>'so_KE','label'=>'Somali (Kenya)', 'flag'=>'ke'),
    array('value'=>'so_SO','label'=>'Somali (Somalia)', 'flag'=>'so'),
    array('value'=>'so','label'=>'Somali', 'flag'=>'so'),
    array('value'=>'es_AR','label'=>'Spanish (Argentina)', 'flag'=>'ar'),
    array('value'=>'es_BO','label'=>'Spanish (Bolivia)', 'flag'=>'bo'),
    array('value'=>'es_CL','label'=>'Spanish (Chile)', 'flag'=>'cl'),
    array('value'=>'es_CO','label'=>'Spanish (Colombia)', 'flag'=>'co'),
    array('value'=>'es_CR','label'=>'Spanish (Costa Rica)', 'flag'=>'cr'),
    array('value'=>'es_DO','label'=>'Spanish (Dominican Republic)', 'flag'=>'do'),
    array('value'=>'es_EC','label'=>'Spanish (Ecuador)', 'flag'=>'ec'),
    array('value'=>'es_SV','label'=>'Spanish (El Salvador)', 'flag'=>'sv'),
    array('value'=>'es_GQ','label'=>'Spanish (Equatorial Guinea)', 'flag'=>'gq'),
    array('value'=>'es_GT','label'=>'Spanish (Guatemala)', 'flag'=>'gt'),
    array('value'=>'es_HN','label'=>'Spanish (Honduras)', 'flag'=>'hn'),
    array('value'=>'es_419','label'=>'Spanish (Latin America)', 'flag'=>'419'),
    array('value'=>'es_MX','label'=>'Spanish (Mexico)', 'flag'=>'mx'),
    array('value'=>'es_NI','label'=>'Spanish (Nicaragua)', 'flag'=>'ni'),
    array('value'=>'es_PA','label'=>'Spanish (Panama)', 'flag'=>'pa'),
    array('value'=>'es_PY','label'=>'Spanish (Paraguay)', 'flag'=>'py'),
    array('value'=>'es_PE','label'=>'Spanish (Peru)', 'flag'=>'pe'),
    array('value'=>'es_PR','label'=>'Spanish (Puerto Rico)', 'flag'=>'pr'),
    array('value'=>'es_ES','label'=>'Spanish (Spain)', 'flag'=>'es'),
    array('value'=>'es_US','label'=>'Spanish (United States)', 'flag'=>'us'),
    array('value'=>'es_UY','label'=>'Spanish (Uruguay)', 'flag'=>'uy'),
    array('value'=>'es_VE','label'=>'Spanish (Venezuela)', 'flag'=>'ve'),
    array('value'=>'es','label'=>'Spanish', 'flag'=>'es'),
    array('value'=>'sw_KE','label'=>'Swahili (Kenya)', 'flag'=>'ke'),
    array('value'=>'sw_TZ','label'=>'Swahili (Tanzania)', 'flag'=>'tz'),
    array('value'=>'sw','label'=>'Swahili', 'flag'=>'sw'),
    array('value'=>'sv_FI','label'=>'Swedish (Finland)', 'flag'=>'fi'),
    array('value'=>'sv_SE','label'=>'Swedish (Sweden)', 'flag'=>'se'),
    array('value'=>'sv','label'=>'Swedish', 'flag'=>'sv'),
    array('value'=>'gsw_CH','label'=>'Swiss German (Switzerland)', 'flag'=>'ch'),
    array('value'=>'gsw','label'=>'Swiss German', 'flag'=>'gsw'),
    array('value'=>'shi_Latn','label'=>'Tachelhit (Latin)', 'flag'=>'latn'),
    array('value'=>'shi_Latn_MA','label'=>'Tachelhit (Latin, Morocco)', 'flag'=>'ma'),
    array('value'=>'shi_Tfng','label'=>'Tachelhit (Tifinagh)', 'flag'=>'tfng'),
    array('value'=>'shi_Tfng_MA','label'=>'Tachelhit (Tifinagh, Morocco)', 'flag'=>'ma'),
    array('value'=>'shi','label'=>'Tachelhit', 'flag'=>'shi'),
    array('value'=>'dav_KE','label'=>'Taita (Kenya)', 'flag'=>'ke'),
    array('value'=>'dav','label'=>'Taita', 'flag'=>'dav'),
    array('value'=>'ta_IN','label'=>'Tamil (India)', 'flag'=>'in'),
    array('value'=>'ta_LK','label'=>'Tamil (Sri Lanka)', 'flag'=>'lk'),
    array('value'=>'ta','label'=>'Tamil', 'flag'=>'ta'),
    array('value'=>'te_IN','label'=>'Telugu (India)', 'flag'=>'in'),
    array('value'=>'te','label'=>'Telugu', 'flag'=>'te'),
    array('value'=>'teo_KE','label'=>'Teso (Kenya)', 'flag'=>'ke'),
    array('value'=>'teo_UG','label'=>'Teso (Uganda)', 'flag'=>'ug'),
    array('value'=>'teo','label'=>'Teso', 'flag'=>'teo'),
    array('value'=>'th_TH','label'=>'Thai (Thailand)', 'flag'=>'th'),
    array('value'=>'th','label'=>'Thai', 'flag'=>'th'),
    array('value'=>'bo_CN','label'=>'Tibetan (China)', 'flag'=>'cn'),
    array('value'=>'bo_IN','label'=>'Tibetan (India)', 'flag'=>'in'),
    array('value'=>'bo','label'=>'Tibetan', 'flag'=>'bo'),
    array('value'=>'ti_ER','label'=>'Tigrinya (Eritrea)', 'flag'=>'er'),
    array('value'=>'ti_ET','label'=>'Tigrinya (Ethiopia)', 'flag'=>'et'),
    array('value'=>'ti','label'=>'Tigrinya', 'flag'=>'ti'),
    array('value'=>'to_TO','label'=>'Tonga (Tonga)', 'flag'=>'to'),
    array('value'=>'to','label'=>'Tonga', 'flag'=>'to'),
    array('value'=>'tr_TR','label'=>'Turkish (Turkey)', 'flag'=>'tr'),
    array('value'=>'tr','label'=>'Turkish', 'flag'=>'tr'),
    array('value'=>'uk_UA','label'=>'Ukrainian (Ukraine)', 'flag'=>'ua'),
    array('value'=>'uk','label'=>'Ukrainian', 'flag'=>'uk'),
    array('value'=>'ur_IN','label'=>'Urdu (India)', 'flag'=>'in'),
    array('value'=>'ur_PK','label'=>'Urdu (Pakistan)', 'flag'=>'pk'),
    array('value'=>'ur','label'=>'Urdu', 'flag'=>'ur'),
    array('value'=>'uz_Arab','label'=>'Uzbek (Arabic)', 'flag'=>'arab'),
    array('value'=>'uz_Arab_AF','label'=>'Uzbek (Arabic, Afghanistan)', 'flag'=>'af'),
    array('value'=>'uz_Cyrl','label'=>'Uzbek (Cyrillic)', 'flag'=>'cyrl'),
    array('value'=>'uz_Cyrl_UZ','label'=>'Uzbek (Cyrillic, Uzbekistan)', 'flag'=>'uz'),
    array('value'=>'uz_Latn','label'=>'Uzbek (Latin)', 'flag'=>'latn'),
    array('value'=>'uz_Latn_UZ','label'=>'Uzbek (Latin, Uzbekistan)', 'flag'=>'uz'),
    array('value'=>'uz','label'=>'Uzbek', 'flag'=>'uz'),
    array('value'=>'vi_VN','label'=>'Vietnamese (Vietnam)', 'flag'=>'vn'),
    array('value'=>'vi','label'=>'Vietnamese', 'flag'=>'vi'),
    array('value'=>'vun_TZ','label'=>'Vunjo (Tanzania)', 'flag'=>'tz'),
    array('value'=>'vun','label'=>'Vunjo', 'flag'=>'vun'),
    array('value'=>'cy_GB','label'=>'Welsh (United Kingdom)', 'flag'=>'gb'),
    array('value'=>'cy','label'=>'Welsh', 'flag'=>'cy'),
    array('value'=>'yo_NG','label'=>'Yoruba (Nigeria)', 'flag'=>'ng'),
    array('value'=>'yo','label'=>'Yoruba', 'flag'=>'yo'),
    array('value'=>'zu_ZA','label'=>'Zulu (South Africa)', 'flag'=>'za'),
    array('value'=>'zu','label'=>'Zulu', 'flag'=>'zu')
);

$global['bcp47'] = array();

foreach ($global['langs_codes'] as $value) {
    $global['bcp47'][$value['value']] = $value;
}

$global['js_availableLangs'] = 'var availableLangs = ' . json_encode($global['langs_codes']) . ';';
