<?php

/**
 * These are just the language codes, not regions. This means it only lists en, not en-US, en-CA etc.
 * @see http://www.iana.org/assignments/language-subtag-registry
 */
$global['langs_codes'] = array(
    array('value' => 'ab', 'label' => 'Abkhaz', 'desc' => 'аҧсуа'),
    array('value' => 'aa', 'label' => 'Afar', 'desc' => 'Afaraf'),
    array('value' => 'af', 'label' => 'Afrikaans', 'desc' => 'Afrikaans'),
    array('value' => 'ak', 'label' => 'Akan', 'desc' => 'Akan'),
    array('value' => 'sq', 'label' => 'Albanian', 'desc' => 'Shqip'),
    array('value' => 'am', 'label' => 'Amharic', 'desc' => 'አማርኛ'),
    array('value' => 'ar', 'label' => 'Arabic', 'desc' => 'العربية'),
    array('value' => 'an', 'label' => 'Aragonese', 'desc' => 'Aragonés'),
    array('value' => 'hy', 'label' => 'Armenian', 'desc' => 'Հայերեն'),
    array('value' => 'as', 'label' => 'Assamese', 'desc' => 'অসমীয়া'),
    array('value' => 'av', 'label' => 'Avaric', 'desc' => 'авар мацӀ, магӀарул мацӀ'),
    array('value' => 'ae', 'label' => 'Avestan', 'desc' => 'avesta'),
    array('value' => 'ay', 'label' => 'Aymara', 'desc' => 'aymar aru'),
    array('value' => 'az', 'label' => 'Azerbaijani', 'desc' => 'azərbaycan dili'),
    array('value' => 'bm', 'label' => 'Bambara', 'desc' => 'bamanankan'),
    array('value' => 'ba', 'label' => 'Bashkir', 'desc' => 'башҡорт теле'),
    array('value' => 'eu', 'label' => 'Basque', 'desc' => 'euskara, euskera'),
    array('value' => 'be', 'label' => 'Belarusian', 'desc' => 'Беларуская'),
    array('value' => 'bn', 'label' => 'Bengali', 'desc' => 'বাংলা'),
    array('value' => 'bh', 'label' => 'Bihari', 'desc' => 'भोजपुरी'),
    array('value' => 'bi', 'label' => 'Bislama', 'desc' => 'Bislama'),
    array('value' => 'bs', 'label' => 'Bosnian', 'desc' => 'bosanski jezik'),
    array('value' => 'br', 'label' => 'Breton', 'desc' => 'brezhoneg'),
    array('value' => 'bg', 'label' => 'Bulgarian', 'desc' => 'български език'),
    array('value' => 'my', 'label' => 'Burmese', 'desc' => 'ဗမာစာ'),
    array('value' => 'ca', 'label' => 'Catalan; Valencian', 'desc' => 'Català'),
    array('value' => 'ch', 'label' => 'Chamorro', 'desc' => 'Chamoru'),
    array('value' => 'ce', 'label' => 'Chechen', 'desc' => 'нохчийн мотт'),
    array('value' => 'ny', 'label' => 'Chichewa; Chewa; Nyanja', 'desc' => 'chiCheŵa, chinyanja'),
    array('value' => 'zh', 'label' => 'Chinese', 'desc' => '中文 (Zhōngwén), 汉语, 漢語'),
    array('value' => 'cv', 'label' => 'Chuvash', 'desc' => 'чӑваш чӗлхи'),
    array('value' => 'kw', 'label' => 'Cornish', 'desc' => 'Kernewek'),
    array('value' => 'co', 'label' => 'Corsican', 'desc' => 'corsu, lingua corsa'),
    array('value' => 'cr', 'label' => 'Cree', 'desc' => 'ᓀᐦᐃᔭᐍᐏᐣ'),
    array('value' => 'hr', 'label' => 'Croatian', 'desc' => 'hrvatski'),
    array('value' => 'cs', 'label' => 'Czech', 'desc' => 'česky, čeština'),
    array('value' => 'da', 'label' => 'Danish', 'desc' => 'dansk'),
    array('value' => 'dv', 'label' => 'Divehi; Dhivehi; Maldivian;', 'desc' => 'ދިވެހި'),
    array('value' => 'nl', 'label' => 'Dutch', 'desc' => 'Nederlands, Vlaams'),
    array('value' => 'en', 'label' => 'English', 'desc' => 'English'),
    array('value' => 'eo', 'label' => 'Esperanto', 'desc' => 'Esperanto'),
    array('value' => 'et', 'label' => 'Estonian', 'desc' => 'eesti, eesti keel'),
    array('value' => 'ee', 'label' => 'Ewe', 'desc' => 'Eʋegbe'),
    array('value' => 'fo', 'label' => 'Faroese', 'desc' => 'føroyskt'),
    array('value' => 'fj', 'label' => 'Fijian', 'desc' => 'vosa Vakaviti'),
    array('value' => 'fi', 'label' => 'Finnish', 'desc' => 'suomi, suomen kieli'),
    array('value' => 'fr', 'label' => 'French', 'desc' => 'français, langue française'),
    array('value' => 'ff', 'label' => 'Fula; Fulah; Pulaar; Pular', 'desc' => 'Fulfulde, Pulaar, Pular'),
    array('value' => 'gl', 'label' => 'Galician', 'desc' => 'Galego'),
    array('value' => 'ka', 'label' => 'Georgian', 'desc' => 'ქართული'),
    array('value' => 'de', 'label' => 'German', 'desc' => 'Deutsch'),
    array('value' => 'el', 'label' => 'Greek, Modern', 'desc' => 'Ελληνικά'),
    array('value' => 'gn', 'label' => 'Guaraní', 'desc' => 'Avañeẽ'),
    array('value' => 'gu', 'label' => 'Gujarati', 'desc' => 'ગુજરાતી'),
    array('value' => 'ht', 'label' => 'Haitian; Haitian Creole', 'desc' => 'Kreyòl ayisyen'),
    array('value' => 'ha', 'label' => 'Hausa', 'desc' => 'Hausa, هَوُسَ'),
    array('value' => 'he', 'label' => 'Hebrew (modern)', 'desc' => 'עברית'),
    array('value' => 'hz', 'label' => 'Herero', 'desc' => 'Otjiherero'),
    array('value' => 'hi', 'label' => 'Hindi', 'desc' => 'हिन्दी, हिंदी'),
    array('value' => 'ho', 'label' => 'Hiri Motu', 'desc' => 'Hiri Motu'),
    array('value' => 'hu', 'label' => 'Hungarian', 'desc' => 'Magyar'),
    array('value' => 'ia', 'label' => 'Interlingua', 'desc' => 'Interlingua'),
    array('value' => 'id', 'label' => 'Indonesian', 'desc' => 'Bahasa Indonesia'),
    array('value' => 'ie', 'label' => 'Interlingue', 'desc' => 'Originally called Occidental; then Interlingue after WWII'),
    array('value' => 'ga', 'label' => 'Irish', 'desc' => 'Gaeilge'),
    array('value' => 'ig', 'label' => 'Igbo', 'desc' => 'Asụsụ Igbo'),
    array('value' => 'ik', 'label' => 'Inupiaq', 'desc' => 'Iñupiaq, Iñupiatun'),
    array('value' => 'io', 'label' => 'Ido', 'desc' => 'Ido'),
    array('value' => 'is', 'label' => 'Icelandic', 'desc' => 'Íslenska'),
    array('value' => 'it', 'label' => 'Italian', 'desc' => 'Italiano'),
    array('value' => 'iu', 'label' => 'Inuktitut', 'desc' => 'ᐃᓄᒃᑎᑐᑦ'),
    array('value' => 'ja', 'label' => 'Japanese', 'desc' => '日本語 (にほんご／にっぽんご)'),
    array('value' => 'jv', 'label' => 'Javanese', 'desc' => 'basa Jawa'),
    array('value' => 'kl', 'label' => 'Kalaallisut, Greenlandic', 'desc' => 'kalaallisut, kalaallit oqaasii'),
    array('value' => 'kn', 'label' => 'Kannada', 'desc' => 'ಕನ್ನಡ'),
    array('value' => 'kr', 'label' => 'Kanuri', 'desc' => 'Kanuri'),
    array('value' => 'ks', 'label' => 'Kashmiri', 'desc' => 'कश्मीरी, كشميري‎'),
    array('value' => 'kk', 'label' => 'Kazakh', 'desc' => 'Қазақ тілі'),
    array('value' => 'km', 'label' => 'Khmer', 'desc' => 'ភាសាខ្មែរ'),
    array('value' => 'ki', 'label' => 'Kikuyu, Gikuyu', 'desc' => 'Gĩkũyũ'),
    array('value' => 'rw', 'label' => 'Kinyarwanda', 'desc' => 'Ikinyarwanda'),
    array('value' => 'ky', 'label' => 'Kirghiz, Kyrgyz', 'desc' => 'кыргыз тили'),
    array('value' => 'kv', 'label' => 'Komi', 'desc' => 'коми кыв'),
    array('value' => 'kg', 'label' => 'Kongo', 'desc' => 'KiKongo'),
    array('value' => 'ko', 'label' => 'Korean', 'desc' => '한국어 (韓國語), 조선말 (朝鮮語)'),
    array('value' => 'ku', 'label' => 'Kurdish', 'desc' => 'Kurdî, كوردی‎'),
    array('value' => 'kj', 'label' => 'Kwanyama, Kuanyama', 'desc' => 'Kuanyama'),
    array('value' => 'la', 'label' => 'Latin', 'desc' => 'latine, lingua latina'),
    array('value' => 'lb', 'label' => 'Luxembourgish, Letzeburgesch', 'desc' => 'Lëtzebuergesch'),
    array('value' => 'lg', 'label' => 'Luganda', 'desc' => 'Luganda'),
    array('value' => 'li', 'label' => 'Limburgish, Limburgan, Limburger', 'desc' => 'Limburgs'),
    array('value' => 'ln', 'label' => 'Lingala', 'desc' => 'Lingála'),
    array('value' => 'lo', 'label' => 'Lao', 'desc' => 'ພາສາລາວ'),
    array('value' => 'lt', 'label' => 'Lithuanian', 'desc' => 'lietuvių kalba'),
    array('value' => 'lu', 'label' => 'Luba-Katanga', 'desc' => ''),
    array('value' => 'lv', 'label' => 'Latvian', 'desc' => 'latviešu valoda'),
    array('value' => 'gv', 'label' => 'Manx', 'desc' => 'Gaelg, Gailck'),
    array('value' => 'mk', 'label' => 'Macedonian', 'desc' => 'македонски јазик'),
    array('value' => 'mg', 'label' => 'Malagasy', 'desc' => 'Malagasy fiteny'),
    array('value' => 'ms', 'label' => 'Malay', 'desc' => 'bahasa Melayu, بهاس ملايو‎'),
    array('value' => 'ml', 'label' => 'Malayalam', 'desc' => 'മലയാളം'),
    array('value' => 'mt', 'label' => 'Maltese', 'desc' => 'Malti'),
    array('value' => 'mi', 'label' => 'Māori', 'desc' => 'te reo Māori'),
    array('value' => 'mr', 'label' => 'Marathi (Marāṭhī)', 'desc' => 'मराठी'),
    array('value' => 'mh', 'label' => 'Marshallese', 'desc' => 'Kajin M̧ajeļ'),
    array('value' => 'mn', 'label' => 'Mongolian', 'desc' => 'монгол'),
    array('value' => 'na', 'label' => 'Nauru', 'desc' => 'Ekakairũ Naoero'),
    array('value' => 'nv', 'label' => 'Navajo, Navaho', 'desc' => 'Diné bizaad, Dinékʼehǰí'),
    array('value' => 'nb', 'label' => 'Norwegian Bokmål', 'desc' => 'Norsk bokmål'),
    array('value' => 'nd', 'label' => 'North Ndebele', 'desc' => 'isiNdebele'),
    array('value' => 'ne', 'label' => 'Nepali', 'desc' => 'नेपाली'),
    array('value' => 'ng', 'label' => 'Ndonga', 'desc' => 'Owambo'),
    array('value' => 'nn', 'label' => 'Norwegian Nynorsk', 'desc' => 'Norsk nynorsk'),
    array('value' => 'no', 'label' => 'Norwegian', 'desc' => 'Norsk'),
    array('value' => 'ii', 'label' => 'Nuosu', 'desc' => 'ꆈꌠ꒿ Nuosuhxop'),
    array('value' => 'nr', 'label' => 'South Ndebele', 'desc' => 'isiNdebele'),
    array('value' => 'oc', 'label' => 'Occitan', 'desc' => 'Occitan'),
    array('value' => 'oj', 'label' => 'Ojibwe, Ojibwa', 'desc' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'),
    array('value' => 'cu', 'label' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'desc' => 'ѩзыкъ словѣньскъ'),
    array('value' => 'om', 'label' => 'Oromo', 'desc' => 'Afaan Oromoo'),
    array('value' => 'or', 'label' => 'Oriya', 'desc' => 'ଓଡ଼ିଆ'),
    array('value' => 'os', 'label' => 'Ossetian, Ossetic', 'desc' => 'ирон æвзаг'),
    array('value' => 'pa', 'label' => 'Panjabi, Punjabi', 'desc' => 'ਪੰਜਾਬੀ, پنجابی‎'),
    array('value' => 'pi', 'label' => 'Pāli', 'desc' => 'पाऴि'),
    array('value' => 'fa', 'label' => 'Persian', 'desc' => 'فارسی'),
    array('value' => 'pl', 'label' => 'Polish', 'desc' => 'polski'),
    array('value' => 'ps', 'label' => 'Pashto, Pushto', 'desc' => 'پښتو'),
    array('value' => 'pt', 'label' => 'Portuguese', 'desc' => 'Português'),
    array('value' => 'qu', 'label' => 'Quechua', 'desc' => 'Runa Simi, Kichwa'),
    array('value' => 'rm', 'label' => 'Romansh', 'desc' => 'rumantsch grischun'),
    array('value' => 'rn', 'label' => 'Kirundi', 'desc' => 'kiRundi'),
    array('value' => 'ro', 'label' => 'Romanian, Moldavian, Moldovan', 'desc' => 'română'),
    array('value' => 'ru', 'label' => 'Russian', 'desc' => 'русский язык'),
    array('value' => 'sa', 'label' => 'Sanskrit (Saṁskṛta)', 'desc' => 'संस्कृतम्'),
    array('value' => 'sc', 'label' => 'Sardinian', 'desc' => 'sardu'),
    array('value' => 'sd', 'label' => 'Sindhi', 'desc' => 'सिन्धी, سنڌي، سندھی‎'),
    array('value' => 'se', 'label' => 'Northern Sami', 'desc' => 'Davvisámegiella'),
    array('value' => 'sm', 'label' => 'Samoan', 'desc' => 'gagana faa Samoa'),
    array('value' => 'sg', 'label' => 'Sango', 'desc' => 'yângâ tî sängö'),
    array('value' => 'sr', 'label' => 'Serbian', 'desc' => 'српски језик'),
    array('value' => 'gd', 'label' => 'Scottish Gaelic; Gaelic', 'desc' => 'Gàidhlig'),
    array('value' => 'sn', 'label' => 'Shona', 'desc' => 'chiShona'),
    array('value' => 'si', 'label' => 'Sinhala, Sinhalese', 'desc' => 'සිංහල'),
    array('value' => 'sk', 'label' => 'Slovak', 'desc' => 'slovenčina'),
    array('value' => 'sl', 'label' => 'Slovene', 'desc' => 'slovenščina'),
    array('value' => 'so', 'label' => 'Somali', 'desc' => 'Soomaaliga, af Soomaali'),
    array('value' => 'st', 'label' => 'Southern Sotho', 'desc' => 'Sesotho'),
    array('value' => 'es', 'label' => 'Spanish; Castilian', 'desc' => 'español, castellano'),
    array('value' => 'su', 'label' => 'Sundanese', 'desc' => 'Basa Sunda'),
    array('value' => 'sw', 'label' => 'Swahili', 'desc' => 'Kiswahili'),
    array('value' => 'ss', 'label' => 'Swati', 'desc' => 'SiSwati'),
    array('value' => 'sv', 'label' => 'Swedish', 'desc' => 'svenska'),
    array('value' => 'ta', 'label' => 'Tamil', 'desc' => 'தமிழ்'),
    array('value' => 'te', 'label' => 'Telugu', 'desc' => 'తెలుగు'),
    array('value' => 'tg', 'label' => 'Tajik', 'desc' => 'тоҷикӣ, toğikī, تاجیکی‎'),
    array('value' => 'th', 'label' => 'Thai', 'desc' => 'ไทย'),
    array('value' => 'ti', 'label' => 'Tigrinya', 'desc' => 'ትግርኛ'),
    array('value' => 'bo', 'label' => 'Tibetan Standard, Tibetan, Central', 'desc' => 'བོད་ཡིག'),
    array('value' => 'tk', 'label' => 'Turkmen', 'desc' => 'Türkmen, Түркмен'),
    array('value' => 'tl', 'label' => 'Tagalog', 'desc' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'),
    array('value' => 'tn', 'label' => 'Tswana', 'desc' => 'Setswana'),
    array('value' => 'to', 'label' => 'Tonga (Tonga Islands)', 'desc' => 'faka Tonga'),
    array('value' => 'tr', 'label' => 'Turkish', 'desc' => 'Türkçe'),
    array('value' => 'ts', 'label' => 'Tsonga', 'desc' => 'Xitsonga'),
    array('value' => 'tt', 'label' => 'Tatar', 'desc' => 'татарча, tatarça, تاتارچا‎'),
    array('value' => 'tw', 'label' => 'Twi', 'desc' => 'Twi'),
    array('value' => 'ty', 'label' => 'Tahitian', 'desc' => 'Reo Tahiti'),
    array('value' => 'ug', 'label' => 'Uighur, Uyghur', 'desc' => 'Uyƣurqə, ئۇيغۇرچە‎'),
    array('value' => 'uk', 'label' => 'Ukrainian', 'desc' => 'українська'),
    array('value' => 'ur', 'label' => 'Urdu', 'desc' => 'اردو'),
    array('value' => 'uz', 'label' => 'Uzbek', 'desc' => 'zbek, Ўзбек, أۇزبېك‎'),
    array('value' => 've', 'label' => 'Venda', 'desc' => 'Tshivenḓa'),
    array('value' => 'vi', 'label' => 'Vietnamese', 'desc' => 'Tiếng Việt'),
    array('value' => 'vo', 'label' => 'Volapük', 'desc' => 'Volapük'),
    array('value' => 'wa', 'label' => 'Walloon', 'desc' => 'Walon'),
    array('value' => 'cy', 'label' => 'Welsh', 'desc' => 'Cymraeg'),
    array('value' => 'wo', 'label' => 'Wolof', 'desc' => 'Wollof'),
    array('value' => 'fy', 'label' => 'Western Frisian', 'desc' => 'Frysk'),
    array('value' => 'xh', 'label' => 'Xhosa', 'desc' => 'isiXhosa'),
    array('value' => 'yi', 'label' => 'Yiddish', 'desc' => 'ייִדיש'),
    array('value' => 'yo', 'label' => 'Yoruba', 'desc' => 'Yorùbá'),
    array('value' => 'za', 'label' => 'Zhuang, Chuang', 'desc' => 'Saɯ cueŋƅ, Saw cuengh')
);

$global['bcp47'] = array();

foreach ($global['langs_codes'] as $value) {
    $global['bcp47'][$value['value']] = $value;
}

$global['js_availableLangs'] = 'var availableLangs = ' . json_encode($global['langs_codes']) . ';';
