<?php
global $global, $config;
if (!isset($global['systemRootPath'])) {
    require_once '../videos/configuration.php';
}
header('Content-Type: application/json');

$obj = new stdClass();
$obj->error = true;
$obj->msg = '';

// Rate limiting: max 20 calls per 5 minutes per caller IP.
// An encoder legitimately hashes a handful of passwords; anything higher
// indicates rainbow-table building or brute force.
enforceRateLimit('encryptPass', 20, 300);

// Require an authenticated admin session OR a valid server-to-server HMAC token.
// The HMAC token is generated by trusted callers (e.g. the Encoder) using the
// shared MySQL password as the secret and a 5-minute time window as the message,
// preventing unauthenticated use while keeping the encoder workflow intact.
$isAuthorized = User::isAdmin();

if (!$isAuthorized) {
    // The HMAC key is $global['webSiteRootURL'] — the only value that is
    // guaranteed to be identical on both the main server and the encoder,
    // regardless of which host each runs on or what DB credentials they use.
    $token = isset($_REQUEST['token']) ? (string) $_REQUEST['token'] : '';
    if ($token !== '' && !empty($global['webSiteRootURL'])) {
        // Accept ±2 windows (each 5 min) to tolerate up to 10 minutes of
        // clock skew between the encoder host and this server.
        $now = (int) floor(time() / 300);
        for ($i = -2; $i <= 2; $i++) {
            $expected = hash_hmac('sha256', (string) ($now + $i), $global['webSiteRootURL']);
            if (hash_equals($expected, $token)) {
                $isAuthorized = true;
                break;
            }
        }
    }
}

if (!$isAuthorized) {
    http_response_code(401);
    $obj->msg = __('Unauthorized');
    die(json_encode($obj));
}

$obj->error = false;
// Intentionally omit the plaintext password from the response to avoid
// unnecessary information disclosure.
$obj->encryptedPassword = encryptPassword($_REQUEST['pass'] ?? '');

echo json_encode($obj);
