SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `videos_statistics` 
ADD COLUMN `created` DATETIME NULL DEFAULT NULL AFTER `videos_id`,
ADD COLUMN `modified` DATETIME NULL DEFAULT NULL AFTER `created`,
ADD COLUMN `lastVideoTime` INT(11) NULL DEFAULT NULL AFTER `modified`;



UPDATE configurations SET  version = '6.3', modified = now() WHERE id = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
