SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- Expand video_password to hold bcrypt hashes (60 chars); VARCHAR(255) future-proofs
-- against longer algorithm outputs per PHP password_hash() documentation.
ALTER TABLE `videos`
MODIFY COLUMN `video_password` VARCHAR(255) NULL DEFAULT NULL;

UPDATE configurations SET version = '29.0', modified = now() WHERE id = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
