-- MySQL Workbench Synchronization
-- Generated: 2017-04-25 15:49
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Daniel

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `configurations` 
ADD COLUMN `ffprobeDuration` VARCHAR(255) NULL DEFAULT NULL AFTER `authCanComment`,
ADD COLUMN `ffmpegImage` VARCHAR(255) NULL DEFAULT NULL AFTER `ffprobeDuration`,
ADD COLUMN `ffmpegMp4` VARCHAR(255) NULL DEFAULT NULL AFTER `ffmpegImage`,
ADD COLUMN `ffmpegWebm` VARCHAR(255) NULL DEFAULT NULL AFTER `ffmpegMp4`,
ADD COLUMN `ffmpegMp3` VARCHAR(255) NULL DEFAULT NULL AFTER `ffmpegWebm`,
ADD COLUMN `ffmpegOgg` VARCHAR(255) NULL DEFAULT NULL AFTER `ffmpegMp3`,
ADD COLUMN `youtubeDl` VARCHAR(255) NULL DEFAULT NULL AFTER `ffmpegOgg`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



UPDATE configurations SET  version = '1.9', modified = now() WHERE id = 1;