<?php

/**
 * Reusable helper for building literal (non-wildcard) SQL LIKE prefix conditions.
 *
 * MySQL treats `%` and `_` as wildcards inside a LIKE pattern. CachesInDB cache
 * names are generated by CachesInDB::hashName(), which replaces every
 * non-alphanumeric character with `_` (e.g. "video/220515221820_v75c8/"
 * becomes "hashName_video_video_220515221820_v75c8_"). Those underscores must
 * be matched literally, otherwise `LIKE 'hashName_video_video_123_%'` can also
 * match unrelated names such as "hashNameXvideoXvideoX123X".
 *
 * This class intentionally has ZERO dependency on configuration.php / the DB
 * layer so it can be required and unit tested in isolation and reused by any
 * other part of the application that needs to build a literal LIKE prefix.
 *
 * Usage:
 *   $escaped = CacheLikeEscaper::escapeLikePrefix($prefix);
 *   ... WHERE name LIKE CONCAT(?, '%') ESCAPE '\\' ...   with $escaped bound as the parameter
 */
class CacheLikeEscaper
{
    const ESCAPE_CHAR = '\\';

    /**
     * Escape LIKE metacharacters (\, %, _) so $value is matched literally when
     * used with `LIKE CONCAT(?, '%') ESCAPE '\\'` (or wrapped with '%...%').
     *
     * @param string $value
     * @return string
     */
    public static function escapeLikePrefix($value)
    {
        $value = (string) $value;
        // Escape the escape character itself first, then the wildcards, so we
        // don't double-escape characters we just introduced.
        $value = str_replace(self::ESCAPE_CHAR, self::ESCAPE_CHAR . self::ESCAPE_CHAR, $value);
        $value = str_replace('%', self::ESCAPE_CHAR . '%', $value);
        $value = str_replace('_', self::ESCAPE_CHAR . '_', $value);
        return $value;
    }
}
