"doNotShowAdsOnThisVideo": $("#doNotShowAdsOnThisVideo").is(":checked"),
"doNotShowAdsOnThisChannel": $("#doNotShowAdsOnThisChannel").is(":checked"),
"redirectVideoCode": $("#redirectVideoCode").val(),
"redirectVideoURL": $("#redirectVideoURL").val(),
"MetaDescription": $("#inputMetaDescription").val(),
"ShortSummary": $("#inputShortSummary").val(),