SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `videos_VR360` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `videos_id` INT NOT NULL,
  `clickAndDrag` TINYINT(1) NULL,
  `showNotice` TINYINT(1) NULL,
  `initLat` INT NULL DEFAULT 0,
  `initLon` INT NULL DEFAULT -180,
  `backToVerticalCenter` TINYINT(1) NULL,
  `videoType` VARCHAR(45) NULL DEFAULT 'equirectangular',
  `active` TINYINT(1) NULL DEFAULT 1,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `videos_id_UNIQUE` (`videos_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
