<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Google_Service_' => array($vendorDir . '/google/apiclient-services/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
);
