-- MySQL Workbench Synchronization
-- Generated: 2017-04-27 15:04
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Daniel

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `configurations` 
ADD COLUMN `ffmpegMp4Portrail` VARCHAR(400) NULL DEFAULT NULL AFTER `ffmpegMp4`,
ADD COLUMN `ffmpegWebmPortrail` VARCHAR(400) NULL DEFAULT NULL AFTER `ffmpegWebm`,
ADD COLUMN `exiftool` VARCHAR(255) NULL DEFAULT NULL AFTER `youtubeDlPath`,
ADD COLUMN `exiftoolPath` VARCHAR(255) NULL DEFAULT NULL AFTER `exiftool`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


UPDATE configurations SET  version = '2.2', modified = now() WHERE id = 1;