BONJOUR – French. Where to say it: ...
HOLA – Spanish. Where to say it: ...
HALLO / GUTEN TAG – German. Where to say it: ...
CIAO – Italian. ...
OLÀ – Portuguese. ...
NAMASTE – Hindi. ...
SALAAM – Persian (Farsi) ...
ZDRAS-TVUY-TE – Russian.

